# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.encrypted
import djangoplugins.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangoplugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('location', models.TextField(blank=True)),
                ('credentials', django_extensions.db.fields.encrypted.EncryptedTextField(blank=True, max_length=None)),
                ('plugin', djangoplugins.fields.PluginField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoplugins.Plugin')),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceMeasurementVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basin3d_datasource', to='basin3d.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('primary_category', models.CharField(max_length=100)),
                ('secondary_category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('broker_id',),
            },
        ),
        migrations.AddField(
            model_name='datasourcemeasurementvariable',
            name='measure_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basin3d_measurementvariable', to='basin3d.MeasurementVariable'),
        ),
        migrations.AlterUniqueTogether(
            name='datasourcemeasurementvariable',
            unique_together={('datasource', 'measure_variable')},
        ),
    ]
