# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basin3d', '0002_change_datasource_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='approach',
        ),
        migrations.DeleteModel(
            name='MeasurementApproach',
        ),
    ]
