# Generated by Django 2.0 on 2019-02-28 16:22

import basin3d.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basin3d', '0004_remove_plugin_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceObservedPropertyVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basin3d_datasource', to='basin3d.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='ObservedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basin3d.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='ObservedPropertyVariable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('categories', basin3d.models.StringListField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='datasourcemeasurementvariable',
            name='datasource',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='observedproperty',
            name='observed_property_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basin3d.ObservedPropertyVariable'),
        ),
        migrations.AddField(
            model_name='observedproperty',
            name='sampling_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basin3d.SamplingMedium'),
        ),
        migrations.AddField(
            model_name='datasourceobservedpropertyvariable',
            name='observed_property_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basin3d_observedpropertyvariable', to='basin3d.ObservedPropertyVariable'),
        ),
        migrations.AlterUniqueTogether(
            name='observedproperty',
            unique_together={('observed_property_variable', 'datasource')},
        ),
        migrations.AlterUniqueTogether(
            name='datasourceobservedpropertyvariable',
            unique_together={('datasource', 'observed_property_variable')},
        ),
    ]
