# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 18:41
from __future__ import unicode_literals

import django_basin3d.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('id_prefix', models.CharField(max_length=5, unique=True)),
                ('location', models.TextField(blank=True)),
                ('plugin_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceMeasurementVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_basin3d_datasource', to='django_basin3d.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementVariable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('categories', django_basin3d.models.StringListField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SamplingMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('abbreviation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='approach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_basin3d.MeasurementApproach'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='django_basin3d.DataSource'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sampling_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_basin3d.SamplingMedium'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_basin3d.MeasurementVariable'),
        ),
        migrations.AddField(
            model_name='datasourcemeasurementvariable',
            name='measure_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_basin3d_measurementvariable', to='django_basin3d.MeasurementVariable'),
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set([('variable', 'datasource')]),
        ),
        migrations.AlterUniqueTogether(
            name='datasourcemeasurementvariable',
            unique_together=set([('datasource', 'measure_variable')]),
        ),
    ]
