# Generated by Django 2.0.13 on 2020-06-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_basin3d', '0005_OGC_Obs_model_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observedpropertyvariable',
            options={'ordering': ('basin3d_id',)},
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='enabled',
        ),
    ]
